SELECT * FROM bbdd_fantasy.tbl_partido;
DELIMITER $$

DROP EVENT IF EXISTS `ACTUALIZAR_PARTIDOS`$$
CREATE EVENT IF NOT EXISTS `ACTUALIZAR_PARTIDOS`
ON SCHEDULE EVERY 1 DAY
STARTS CONCAT(CURDATE(), ' 13:00:00')
ON COMPLETION PRESERVE
ENABLE
DO
BEGIN
    UPDATE TBL_PARTIDO AS P
    INNER JOIN (
        SELECT ID_PARTIDO, SUM(J.ATAQUE + J.DEFENSA) AS PUNTOS_LOCAL
        FROM TBL_PARTIDO AS P
        INNER JOIN TBL_JUGADOR_EQUIPO AS JE ON P.EQUIPO_LOCAL = JE.ID_EQUIPO
        INNER JOIN TBL_JUGADORES AS J ON JE.ID_JUGADOR = J.ID_JUGADOR 
        WHERE P.FECHA_INICIO = CURDATE() AND JE.ALINEADO = "SI"
        GROUP BY P.ID_PARTIDO
    ) AS PL ON P.ID_PARTIDO = PL.ID_PARTIDO
    SET P.PUNTOS_LOCAL = PL.PUNTOS_LOCAL;

    UPDATE TBL_PARTIDO AS P
    INNER JOIN (
        SELECT ID_PARTIDO, SUM(J.ATAQUE + J.DEFENSA) AS PUNTOS_VISITANTE
        FROM TBL_PARTIDO AS P
        INNER JOIN TBL_JUGADOR_EQUIPO AS JE ON P.EQUIPO_VISITANTE = JE.ID_EQUIPO
        INNER JOIN TBL_JUGADORES AS J ON JE.ID_JUGADOR = J.ID_JUGADOR 
        WHERE P.FECHA_INICIO = CURDATE() AND JE.ALINEADO = "SI"
        GROUP BY P.ID_PARTIDO
    ) AS PV ON P.ID_PARTIDO = PV.ID_PARTIDO
    SET P.PUNTOS_VISITANTE = PV.PUNTOS_VISITANTE;
    
END$$

DELIMITER ;