/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author a22marcorr
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        pnlCrearCuenta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuInicial = new javax.swing.JInternalFrame();
        panelMenuButtons = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlCrearCuenta = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlClasificacion = new javax.swing.JPanel();
        pnlalineacion = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuInicial.setVisible(true);
        pnlMenuInicial.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Iniciar sesion");
        panelMenuButtons.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 132, 59));

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        panelMenuButtons.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 132, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("La Liga Fantasy");
        panelMenuButtons.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 348, 99));

        pnlMenuInicial.getContentPane().add(panelMenuButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 500));

        pnlCrearCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCrearCuenta.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 70));
        pnlCrearCuenta.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 50));

        jButton3.setText("Crear cuenta");
        pnlCrearCuenta.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 180, 80));

        jLabel2.setText("Nombre usuario");
        pnlCrearCuenta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel3.setText("Contraseña");
        pnlCrearCuenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        pnlMenuInicial.getContentPane().add(pnlCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 500));

        getContentPane().add(pnlMenuInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 49, -1, -1));

        javax.swing.GroupLayout pnlClasificacionLayout = new javax.swing.GroupLayout(pnlClasificacion);
        pnlClasificacion.setLayout(pnlClasificacionLayout);
        pnlClasificacionLayout.setHorizontalGroup(
            pnlClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        pnlClasificacionLayout.setVerticalGroup(
            pnlClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(pnlClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 180, 590));

        javax.swing.GroupLayout pnlalineacionLayout = new javax.swing.GroupLayout(pnlalineacion);
        pnlalineacion.setLayout(pnlalineacionLayout);
        pnlalineacionLayout.setHorizontalGroup(
            pnlalineacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pnlalineacionLayout.setVerticalGroup(
            pnlalineacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(pnlalineacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 490, 430));

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        pnlCrearCuenta.setVisible(true);
        panelMenuButtons.setVisible(false);
        
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelMenuButtons;
    private javax.swing.JPanel pnlClasificacion;
    private javax.swing.JPanel pnlCrearCuenta;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JInternalFrame pnlMenuInicial;
    private javax.swing.JPanel pnlalineacion;
    // End of variables declaration//GEN-END:variables
}
