/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author a22marcorr
 */
public class pantallaIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form pantallaIniciarSesion
     */
    public pantallaIniciarSesion() {
        initComponents();
        radioBtnGrpOptions.add(radioCorreo);
        radioBtnGrpOptions.add(radioUsername);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGrpOptions = new javax.swing.ButtonGroup();
        BG = new javax.swing.JLayeredPane();
        lblCrearCuenta = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        separatorContraseña = new javax.swing.JSeparator();
        txtCCContraseña = new javax.swing.JPasswordField();
        btnCCCreate = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        separatorUsername = new javax.swing.JSeparator();
        txtCCUsername = new javax.swing.JTextField();
        radioUsername = new javax.swing.JRadioButton();
        radioCorreo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(206, 206, 206));
        BG.setOpaque(true);
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCrearCuenta.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(92, 99, 112));
        lblCrearCuenta.setText("INICIAR SESION");
        BG.add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 390, 60));

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(92, 99, 112));
        lblContraseña.setText("Contraseña");
        BG.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));
        BG.add(separatorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 260, 10));

        txtCCContraseña.setBackground(new java.awt.Color(206, 206, 206));
        txtCCContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCContraseña.setBorder(null);
        txtCCContraseña.setMaximumSize(new java.awt.Dimension(64, 22));
        BG.add(txtCCContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 260, 50));

        btnCCCreate.setBackground(new java.awt.Color(45, 89, 141));
        btnCCCreate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCCCreate.setForeground(new java.awt.Color(206, 206, 206));
        btnCCCreate.setText("Crear cuenta");
        BG.add(btnCCCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 180, 80));

        lblUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(92, 99, 112));
        lblUsername.setText("Nombre usuario");
        BG.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));
        BG.add(separatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 260, 10));

        txtCCUsername.setBackground(new java.awt.Color(206, 206, 206));
        txtCCUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCCUsername.setBorder(null);
        txtCCUsername.setMaximumSize(new java.awt.Dimension(64, 22));
        BG.add(txtCCUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 260, 50));

        radioUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        radioUsername.setForeground(new java.awt.Color(92, 99, 112));
        radioUsername.setText("Nombre de usuario");
        radioUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioUsernameMouseEntered(evt);
            }
        });
        radioUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUsernameActionPerformed(evt);
            }
        });
        BG.add(radioUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        radioCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        radioCorreo.setForeground(new java.awt.Color(92, 99, 112));
        radioCorreo.setText("Correo electronico");
        radioCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorreoActionPerformed(evt);
            }
        });
        BG.add(radioCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioUsernameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_radioUsernameMouseEntered

    private void radioUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUsernameActionPerformed
        // TODO add your handling code here:
        lblUsername.setText("Nombre usuario");
    }//GEN-LAST:event_radioUsernameActionPerformed

    private void radioCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorreoActionPerformed
        // TODO add your handling code here:
         lblUsername.setText("Correo electronico");
    }//GEN-LAST:event_radioCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BG;
    private javax.swing.JButton btnCCCreate;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblUsername;
    private javax.swing.ButtonGroup radioBtnGrpOptions;
    private javax.swing.JRadioButton radioCorreo;
    private javax.swing.JRadioButton radioUsername;
    private javax.swing.JSeparator separatorContraseña;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JPasswordField txtCCContraseña;
    private javax.swing.JTextField txtCCUsername;
    // End of variables declaration//GEN-END:variables
}
