/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.juego;

import Interface.menus.Menu;
import Methods.Liga;
import Methods.Usuario;
import OperacionesBBDD.OperacionesBBDD;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marco
 */
public class PantallaLiga extends javax.swing.JFrame {

    /**
     * Creates new form PantallaLiga
     */
    Usuario Actual = null;

    public PantallaLiga(Usuario us1) {
        initComponents();
        Actual = us1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerBG = new javax.swing.JLayeredPane();
        panelAcciones = new javax.swing.JLayeredPane();
        btnRetroceder = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        layerMenu = new javax.swing.JLayeredPane();
        btnHome = new javax.swing.JButton();
        btnPlantilla = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnClasificacion = new javax.swing.JButton();
        btnBuscarJugador = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnLiga = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        layerUnirseLiga = new javax.swing.JLayeredPane();
        btnUnirseLiga = new javax.swing.JButton();
        txtNombreUnirseLiga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInfoUnirse = new javax.swing.JButton();
        layerInfoCrearLiga = new javax.swing.JLayeredPane();
        btnCrearLiga = new javax.swing.JButton();
        txtNombreCrearLiga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInfoCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setShape(new RoundRectangle2D.Double(0, 0, 900, 700, 50, 50));

        layerBG.setBackground(new java.awt.Color(206, 206, 206));
        layerBG.setOpaque(true);
        layerBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAcciones.setMaximumSize(new java.awt.Dimension(95, 25));
        panelAcciones.setMinimumSize(new java.awt.Dimension(95, 25));

        btnRetroceder.setBackground(new java.awt.Color(206, 206, 206));
        btnRetroceder.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnRetroceder.setForeground(new java.awt.Color(153, 0, 0));
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retroceder.png"))); // NOI18N
        btnRetroceder.setBorder(null);
        btnRetroceder.setBorderPainted(false);
        btnRetroceder.setContentAreaFilled(false);
        btnRetroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRetroceder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRetroceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetroceder.setOpaque(true);
        btnRetroceder.setRequestFocusEnabled(false);
        btnRetroceder.setRolloverEnabled(false);
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(206, 206, 206));
        btnMinimizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(153, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar (1).png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setOpaque(true);
        btnMinimizar.setRequestFocusEnabled(false);
        btnMinimizar.setRolloverEnabled(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(206, 206, 206));
        btnClose.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(153, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close (1).png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setOpaque(true);
        btnClose.setRequestFocusEnabled(false);
        btnClose.setRolloverEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        panelAcciones.setLayer(btnRetroceder, javax.swing.JLayeredPane.POPUP_LAYER);
        panelAcciones.setLayer(btnMinimizar, javax.swing.JLayeredPane.POPUP_LAYER);
        panelAcciones.setLayer(btnClose, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetroceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRetroceder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        layerBG.add(panelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 30));
        layerBG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 860, 10));

        layerMenu.setBackground(new java.awt.Color(206, 206, 206));
        layerMenu.setOpaque(true);
        layerMenu.setLayout(new java.awt.GridLayout(1, 0));

        btnHome.setBackground(new java.awt.Color(206, 206, 206));
        btnHome.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_90px.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        btnHome.setName(""); // NOI18N
        btnHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_90px.click.png"))); // NOI18N
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_90px.hover.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        btnHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnHomeKeyReleased(evt);
            }
        });
        layerMenu.add(btnHome);

        btnPlantilla.setBackground(new java.awt.Color(206, 206, 206));
        btnPlantilla.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPlantilla.setForeground(new java.awt.Color(0, 0, 0));
        btnPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stadium_90px.png"))); // NOI18N
        btnPlantilla.setBorder(null);
        btnPlantilla.setBorderPainted(false);
        btnPlantilla.setContentAreaFilled(false);
        btnPlantilla.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stadium_90px.click.png"))); // NOI18N
        btnPlantilla.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stadium_90px.hover.png"))); // NOI18N
        layerMenu.add(btnPlantilla);

        btnPerfil.setBackground(new java.awt.Color(206, 206, 206));
        btnPerfil.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.click.png"))); // NOI18N
        btnPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.hover.png"))); // NOI18N
        layerMenu.add(btnPerfil);

        btnClasificacion.setBackground(new java.awt.Color(206, 206, 206));
        btnClasificacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnClasificacion.setForeground(new java.awt.Color(0, 0, 0));
        btnClasificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N
        btnClasificacion.setBorder(null);
        btnClasificacion.setBorderPainted(false);
        btnClasificacion.setContentAreaFilled(false);
        btnClasificacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.click.png"))); // NOI18N
        btnClasificacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.hover.png"))); // NOI18N
        layerMenu.add(btnClasificacion);

        btnBuscarJugador.setBackground(new java.awt.Color(206, 206, 206));
        btnBuscarJugador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarJugador.setBorder(null);
        btnBuscarJugador.setBorderPainted(false);
        btnBuscarJugador.setContentAreaFilled(false);
        btnBuscarJugador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.click.png"))); // NOI18N
        btnBuscarJugador.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.hover.png"))); // NOI18N
        layerMenu.add(btnBuscarJugador);

        btnTienda.setBackground(new java.awt.Color(206, 206, 206));
        btnTienda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnTienda.setForeground(new java.awt.Color(0, 0, 0));
        btnTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tienda.png"))); // NOI18N
        btnTienda.setBorder(null);
        btnTienda.setBorderPainted(false);
        btnTienda.setContentAreaFilled(false);
        btnTienda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tienda.click.png"))); // NOI18N
        btnTienda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tienda.hover.png"))); // NOI18N
        layerMenu.add(btnTienda);

        btnLiga.setBackground(new java.awt.Color(206, 206, 206));
        btnLiga.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnLiga.setForeground(new java.awt.Color(0, 0, 0));
        btnLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_90px.png"))); // NOI18N
        btnLiga.setBorder(null);
        btnLiga.setBorderPainted(false);
        btnLiga.setContentAreaFilled(false);
        btnLiga.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_90px.click.png"))); // NOI18N
        btnLiga.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_90px.hover.png"))); // NOI18N
        layerMenu.add(btnLiga);

        btnExit.setBackground(new java.awt.Color(206, 206, 206));
        btnExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.press.png"))); // NOI18N
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.hover.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        layerMenu.add(btnExit);

        layerBG.add(layerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 100));

        layerUnirseLiga.setBackground(new java.awt.Color(92, 99, 112));
        layerUnirseLiga.setMaximumSize(new java.awt.Dimension(410, 510));
        layerUnirseLiga.setMinimumSize(new java.awt.Dimension(410, 510));
        layerUnirseLiga.setOpaque(true);
        layerUnirseLiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnirseLiga.setBackground(new java.awt.Color(206, 206, 206));
        btnUnirseLiga.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnUnirseLiga.setForeground(new java.awt.Color(0, 0, 0));
        btnUnirseLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telegram_app_150px.png"))); // NOI18N
        btnUnirseLiga.setBorder(null);
        btnUnirseLiga.setBorderPainted(false);
        btnUnirseLiga.setContentAreaFilled(false);
        btnUnirseLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnirseLiga.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        btnUnirseLiga.setName(""); // NOI18N
        btnUnirseLiga.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telegram_app_150px.click.png"))); // NOI18N
        btnUnirseLiga.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telegram_app_150px.hover.png"))); // NOI18N
        btnUnirseLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseLigaActionPerformed(evt);
            }
        });
        btnUnirseLiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnUnirseLigaKeyReleased(evt);
            }
        });
        layerUnirseLiga.add(btnUnirseLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));
        layerUnirseLiga.add(txtNombreUnirseLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, 60));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setText("UNIRSE A UNA LIGA");
        layerUnirseLiga.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 360, 80));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Nombre de la liga");
        layerUnirseLiga.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, 30));

        btnInfoUnirse.setBackground(new java.awt.Color(92, 99, 112));
        btnInfoUnirse.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInfoUnirse.setForeground(new java.awt.Color(153, 0, 0));
        btnInfoUnirse.setBorder(null);
        btnInfoUnirse.setBorderPainted(false);
        btnInfoUnirse.setContentAreaFilled(false);
        btnInfoUnirse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInfoUnirse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnInfoUnirse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfoUnirse.setMaximumSize(new java.awt.Dimension(390, 80));
        btnInfoUnirse.setMinimumSize(new java.awt.Dimension(390, 80));
        btnInfoUnirse.setOpaque(true);
        btnInfoUnirse.setPreferredSize(new java.awt.Dimension(390, 80));
        btnInfoUnirse.setRequestFocusEnabled(false);
        btnInfoUnirse.setRolloverEnabled(false);
        btnInfoUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUnirseActionPerformed(evt);
            }
        });
        layerUnirseLiga.setLayer(btnInfoUnirse, javax.swing.JLayeredPane.POPUP_LAYER);
        layerUnirseLiga.add(btnInfoUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 80));

        layerInfoCrearLiga.setBackground(new java.awt.Color(92, 99, 112));
        layerInfoCrearLiga.setMaximumSize(new java.awt.Dimension(410, 510));
        layerInfoCrearLiga.setMinimumSize(new java.awt.Dimension(410, 510));
        layerInfoCrearLiga.setOpaque(true);
        layerInfoCrearLiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearLiga.setBackground(new java.awt.Color(206, 206, 206));
        btnCrearLiga.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCrearLiga.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearLiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_150px.png"))); // NOI18N
        btnCrearLiga.setBorder(null);
        btnCrearLiga.setBorderPainted(false);
        btnCrearLiga.setContentAreaFilled(false);
        btnCrearLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearLiga.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        btnCrearLiga.setName(""); // NOI18N
        btnCrearLiga.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_150px.click.png"))); // NOI18N
        btnCrearLiga.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_150px.hover.png"))); // NOI18N
        btnCrearLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLigaActionPerformed(evt);
            }
        });
        btnCrearLiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnCrearLigaKeyReleased(evt);
            }
        });
        layerInfoCrearLiga.add(btnCrearLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        layerInfoCrearLiga.add(txtNombreCrearLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 320, 60));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setText("CREAR A UNA LIGA");
        layerInfoCrearLiga.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 360, 80));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de la liga");
        layerInfoCrearLiga.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 30));

        btnInfoCrear.setBackground(new java.awt.Color(92, 99, 112));
        btnInfoCrear.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInfoCrear.setForeground(new java.awt.Color(153, 0, 0));
        btnInfoCrear.setBorder(null);
        btnInfoCrear.setBorderPainted(false);
        btnInfoCrear.setContentAreaFilled(false);
        btnInfoCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInfoCrear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnInfoCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfoCrear.setMaximumSize(new java.awt.Dimension(390, 80));
        btnInfoCrear.setMinimumSize(new java.awt.Dimension(390, 80));
        btnInfoCrear.setOpaque(true);
        btnInfoCrear.setPreferredSize(new java.awt.Dimension(390, 80));
        btnInfoCrear.setRequestFocusEnabled(false);
        btnInfoCrear.setRolloverEnabled(false);
        btnInfoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoCrearActionPerformed(evt);
            }
        });
        layerInfoCrearLiga.setLayer(btnInfoCrear, javax.swing.JLayeredPane.POPUP_LAYER);
        layerInfoCrearLiga.add(btnInfoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 80));

        jLayeredPane1.setLayer(layerUnirseLiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(layerInfoCrearLiga, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layerInfoCrearLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(layerUnirseLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layerInfoCrearLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layerUnirseLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layerBG.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 870, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layerBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layerBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseLigaActionPerformed
        if (!txtNombreUnirseLiga.getText().isEmpty()) {

            String NombreLiga = txtNombreUnirseLiga.getText();

            String sentenciaSelect = "SELECT NOMBRE, (SELECT USUARIO FROM TBL_USUARIO  WHERE ID_USUARIO=ADMINISTRADOR)FROM TBL_LIGA WHERE NOMBRE='" + NombreLiga + "';";

            OperacionesBBDD get = new OperacionesBBDD();
            ResultSet results = get.getSQL(sentenciaSelect);

            try {
                if (results.next()) {
                    System.out.println("aa:" + results.getString(1));

                    Liga liga1 = new Liga(results.getString(1), results.getString(1));
                    if (liga1.getNombre().equalsIgnoreCase(NombreLiga) && results != null ) {
                        String insertString2 = " UPDATE bbdd_fantasy.tbl_usuario SET LIGA_INSCRITO=(SELECT  L.ID_LIGA FROM TBL_LIGA AS L WHERE L.NOMBRE='" + NombreLiga + "') WHERE USUARIO='" + Actual.getNombreUsuario() + "';";

                        System.out.println(insertString2);
                        OperacionesBBDD escritura2 = new OperacionesBBDD();
                        escritura2.escrituraSql(insertString2);

                        btnInfoUnirse.setForeground(new java.awt.Color(0, 100, 0));
                        btnInfoUnirse.setVisible(true);
                        btnInfoUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INSERT.png")));
                        btnInfoUnirse.setText("Te has unido con exito a la liga: " + NombreLiga);

                    } 

                }else {
                        btnInfoUnirse.setForeground(new java.awt.Color(100, 0, 0));
                        btnInfoUnirse.setVisible(true);
                        btnInfoUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
                        btnInfoUnirse.setText("La liga no existe");

                    }

            } catch (SQLException ex) {
                Logger.getLogger(PantallaLiga.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnUnirseLigaActionPerformed

    private void btnUnirseLigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUnirseLigaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUnirseLigaKeyReleased

    private void btnCrearLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLigaActionPerformed
        // TODO add your handling code here:

        String NombreLiga = txtNombreCrearLiga.getText();

        String insertString = "INSERT INTO bbdd_fantasy.tbl_liga (NOMBRE, ADMINISTRADOR) VALUES ('" + NombreLiga + "', (select id_usuario from tbl_usuario where  usuario='" + Actual.getNombreUsuario() + "'));";

        System.out.println(insertString);
        OperacionesBBDD escritura = new OperacionesBBDD();
        escritura.escrituraSql(insertString);

        String insertString2 = " UPDATE bbdd_fantasy.tbl_usuario SET LIGA_INSCRITO=(SELECT  L.ID_LIGA FROM TBL_LIGA AS L WHERE L.NOMBRE='" + NombreLiga + "') WHERE USUARIO='" + Actual.getNombreUsuario() + "';";

        System.out.println(insertString2);
        OperacionesBBDD escritura2 = new OperacionesBBDD();
        if(escritura2.escrituraSql(insertString2)){
            btnInfoUnirse.setForeground(new java.awt.Color(0, 100, 0));
                        btnInfoUnirse.setVisible(true);
                        btnInfoUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INSERT.png")));
                        btnInfoUnirse.setText("Has creado con exito la liga: " + NombreLiga);
            
        }else{
            btnInfoUnirse.setForeground(new java.awt.Color(100, 0, 0));
                        btnInfoUnirse.setVisible(true);
                        btnInfoUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
                        btnInfoUnirse.setText("La liga no existe");

        }
        

    }//GEN-LAST:event_btnCrearLigaActionPerformed

    private void btnCrearLigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCrearLigaKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_btnCrearLigaKeyReleased

    private void btnInfoUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUnirseActionPerformed
        // TODO add your handling code here:
        btnInfoUnirse.setVisible(false);
    }//GEN-LAST:event_btnInfoUnirseActionPerformed

    private void btnInfoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoCrearActionPerformed
        // TODO add your handling code here:
         btnInfoCrear.setVisible(false);
    }//GEN-LAST:event_btnInfoCrearActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        pantallaSesionIniciada pantalla = new pantallaSesionIniciada(Actual);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Menu pantalla = new Menu();
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHomeKeyReleased
        // TODO add your handling code here:
        //        btnHome.setIcon(home_90px.hover);
    }//GEN-LAST:event_btnHomeKeyReleased

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarJugador;
    private javax.swing.JButton btnClasificacion;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCrearLiga;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInfoCrear;
    private javax.swing.JButton btnInfoUnirse;
    private javax.swing.JButton btnLiga;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnPlantilla;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnTienda;
    private javax.swing.JButton btnUnirseLiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLayeredPane layerBG;
    private javax.swing.JLayeredPane layerInfoCrearLiga;
    private javax.swing.JLayeredPane layerMenu;
    private javax.swing.JLayeredPane layerUnirseLiga;
    private javax.swing.JLayeredPane panelAcciones;
    private javax.swing.JTextField txtNombreCrearLiga;
    private javax.swing.JTextField txtNombreUnirseLiga;
    // End of variables declaration//GEN-END:variables
}
